name: Deploy to GH Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      upload-pages-artifact: true
  deploy-to-release:
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions: write-all
    steps:
      - name: Download Pages Artifact
        uses: actions/download-artifact@v2
        with:
          name: app-artifact
      - run: ls -R
      - run: tar -czvf artifact.tar dist/
      - name: Package app
        run: zip -r app.zip dist/
      - name: version
        run: echo "::set-output name=version::$(./bin/azblogfilter --version)"
        id: version
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body: |
            Automatic release triggered manually
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app.zip
          asset_name: app.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ github.token }}

